apiVersion: v1
kind: Pod
metadata:
  annotations:
  labels:
    app: clair
  name: clair-and-postgres
  namespace: clair
spec:
  containers:
  - image: quay.io/coreos/clair:v2.0.3
    args:
    - -config
    - /config/config.yaml
    imagePullPolicy: Always
    name: clair
    ports:
    - containerPort: 6060
      protocol: TCP
    - containerPort: 6061
      protocol: TCP
    volumeMounts:
    - mountPath: /config
      name: clair-config
  - image: postgres:9.6
    env:
    - name: POSTGRES_PASSWORD
      value: peq8444dcUBJ6XLv
    imagePullPolicy: IfNotPresent
    name: postgres
    ports:
    - containerPort: 5432
      name: postgres-port
      protocol: TCP
  restartPolicy: Always
  volumes:
    - name: clair-config
      configMap:
        name: clair-config

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: clair-config
  namespace: clair
data:
  config.yaml: |-
    clair:
      database:
        type: pgsql
        options:
          source: host=localhost port=5432 user=postgres password=peq8444dcUBJ6XLv sslmode=disable statement_timeout=60000
        cacheSize: 16384
      api:
        port: 6060
        healthport: 6061
        timeout: 900s
      updater:
        interval: 6h
      notifier:
        attempts: 3
        renotifyInterval: 2h

---

apiVersion: v1
kind: Service
metadata:
  name: clairsvc
  namespace: clair
  labels:
    app: clair
spec:
  type: NodePort
  ports:
  - port: 6060
    protocol: TCP
    nodePort: 30060
    name: clair-port0
  - port: 6061
    protocol: TCP
    nodePort: 30061
    name: clair-port1
  selector:
    app: clair