version: "3"

services:
  postgres:
    image: arminc/clair-db
    restart: unless-stopped
    networks:
       - net_clair
  clair:
    image: quay.io/coreos/clair:v2.0.7
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "6060-6061:6060-6061"
    volumes:
      - ./config.yaml:/config/config.yaml
    command: [-config, /config/config.yaml, --insecure-tls, --log-level=debug]
    networks:
      - net_clair
  klar:
    build:
      context: ./klar/
    networks:
      - net_clair
  localscannerapi:
    build:
      context: ../
      dockerfile: multistage.Dockerfile
    ports:
      - "8080:80"
    networks:
      - net_clair
    environment:
      - Dockerhub__Username=SET_THIS
      - Dockerhub__Password=SET_THIS
      - Google__GcrJsonKeyPath=/var/gcrkey/key.json
      - AppRootUri=http://localhost:8080/doc/
      - ConnectionString=host=postgres port=5432 user=postgres password=password sslmode=disable statement_timeout=60000
      - Logging__LogLevel__Default=Debug
  stablescanerapi:
    image: ptcos/container-vulnerability-scanner:0.1.1
    ports:
      - "8181:80"
    networks:
      - net_clair
    environment:
      - Dockerhub__Username=SET_THIS
      - Dockerhub__Password=SET_THIS
      - Google__GcrJsonKeyPath=/var/gcrkey/key.json
      - AppRootUri=http://localhost:8080/doc/
      - ConnectionString=host=postgres port=5432 user=postgres password=password sslmode=disable statement_timeout=60000
      - Logging__LogLevel__Default=Debug
networks:
  net_clair:

